# Generated by Django 4.1.5 on 2023-01-10 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlstore_back', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
