# Generated by Django 4.1.5 on 2023-01-11 16:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tlstore_back', '0002_delete_teste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_number', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)])),
                ('street', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('neighborhood', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('season', models.CharField(max_length=40)),
                ('img', models.CharField(max_length=50)),
                ('isImportant', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('addresID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tlstore_back.adress')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tlstore_back.categories')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tlstore_back.countries')),
            ],
        ),
        migrations.CreateModel(
            name='Sells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tlstore_back.products')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tlstore_back.users')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tlstore_back.teams'),
        ),
    ]
